# Generated by Django 4.1.7 on 2023-03-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_tagged_product_tagged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
