# Generated by Django 4.1.7 on 2023-04-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productgallary_delete_productgalary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGallary',
            new_name='ProductGallery',
        ),
    ]
